# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HRMS' do

pod 'Realm', '~> 0.98.2'

end

